name: Test Email Action

on:
  push:
    branches:
      - main  # Or any branch you want to trigger this on

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: 22f2001149@ds.study.iitm.ac.in
        run: echo "Hello, world!"
